version: 2
jobs:
  provisionAZWebApp:
    docker:
    - image: microsoft/azure-cli:latest
    steps:
    - run: |
        az login --service-principal -u $AZURE_SERVICE_PRINC --password $AZURE_SERVICE_PRINC_PASSWORD --tenant $AZURE_TENANT
        az appservice plan create -g $AZ_RESOURCE_GRP -n $AZ_SERVICE_PLAN
        az webapp create -g $AZ_RESOURCE_GRP -p $AZ_SERVICE_PLAN -n $AZ_WEBAPP_NAME --deployment-container-image-name "sonarqube"
workflows:
  version: 2
  build_Infra:
    jobs:
    - provisionAZWebApp
